#!/bin/sh
set -e

# Try to get the default branch name (master/main)
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')

if [ -z "$DEFAULT_BRANCH" ]; then
    DEFAULT_BRANCH='master'
fi

DEFAULT_BRANCH_CHANGE_IDS="$(git log $DEFAULT_BRANCH | grep Change-Id: )"
for BRANCH in $( git branch | cut -c 3- | grep -v "^$DEFAULT_BRANCH$" )
do
	ID="$(git log -n1 "$BRANCH" | grep Change-Id: | head -n1)"
	if echo "$DEFAULT_BRANCH_CHANGE_IDS" | grep "$ID" > /dev/null; then
		git branch -D "$BRANCH"
	else
		echo "Kept branch $BRANCH"
	fi
done
